## 📦 Library Imports & Environment Setup This section loads all essential Python libraries required for data processing, numerical computation, and file system access. It also verifies the availability an****d structure of the input dataset directories provided by Kaggle.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_49.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_67_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_90.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_77.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_20_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_66.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_54.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_106_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_42.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_81.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_72.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_107.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_79.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_83.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_88.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_164.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_116_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_60.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_55.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_25.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_112.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_153_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_132.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_44.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_7.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_119.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_106.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_20.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_59.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_129.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_12.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_31.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_97.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_102_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_40.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_157.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_29.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_37.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_25_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_67.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_132_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_94.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_82.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_61.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_27.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_141.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_100.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_32.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_110.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_19_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_50.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_120.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_113.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_17_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_10_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_56.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_114.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_104.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_71.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_28.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_76.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_96_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_57.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_102.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_149.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_45.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_156_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_41.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_61_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_86.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_2.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_79_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_161.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_4.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_162.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_118.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_52_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_19.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_89.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_70.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_87.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_75.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_84.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_95.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_23.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_159.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_137.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_56_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_93.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_142.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_143.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_156.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_14.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_5.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_80.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_13.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_8.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_22.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_85.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_126.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_133_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_38.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_152.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_31_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_47.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_148.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_111.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_127.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_16_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_99_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_130.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_140_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_96.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_98.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_146.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_52.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_16.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_158_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_78.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_101.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_26.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_30.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_158.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_140.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_17.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_154.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_24.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_6.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_92.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_69.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_64.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_131.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_105.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_21.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_35.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_160.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_15.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_63.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_122.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_30_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_125.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_115.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_13_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_68.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_138.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_86_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_155.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_10.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_121.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_48.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_146_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_117.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_11.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_153.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_145.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_39.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_103.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_136.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_46.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_147.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_144.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_135_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_76_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_139.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_161_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_134.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_62.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_18.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_116.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_123.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_133.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_135.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_108.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_109.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_34.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_53.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_150.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_73.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_43.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_99.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_32_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_124.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_9.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_3.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_136_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_65.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_57_1.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_33.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_58.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_128.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_36.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_74.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_51.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_163.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_91.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test/audio_151.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_49.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_77_2.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_90.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_77.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_66.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_54.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_237.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_42.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_257.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_256_2.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_81.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_330.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_72.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_232_2.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_328.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_107.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_79.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_73_2.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_83.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_88.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_164.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_283.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_300.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_315.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_60.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_55.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_204.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_25.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_112.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_176.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_256.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_359.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_132.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_44.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_290.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_7.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_234.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_120_2.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_119.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_321.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_106.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_20.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_59.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_129.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_12.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_40_2.wav
/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train/audio_369_2.wav

## 📦 Library Imports & Environment Setup This section loads all essential Python libraries required for data processing, numerical computation, and file system access. It also verifies the availability an****d structure of the input dataset directories provided by Kaggle.

In [2]:
# ===============================
# Environment Setup (RUN FIRST)
# ===============================
!pip install -U openai-whisper
!pip install language-tool-python==2.7.1
!pip install spacy happytransformer lightgbm librosa soundfile
!python -m spacy download en_core_web_sm

Collecting openai-whisper
  Downloading openai_whisper-20250625.tar.gz (803 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 26.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: more-itertools in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.60.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.0.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (0.12.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (2.8.0+cu126)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (4.67.1)
Requirement already satisfied: triton>=2 in /usr/local/lib/python3.12/dist-packages (from openai-whisper) (3.4.0)
Requirement already satisfied: setuptools>=40.8.0 in /usr/local/lib/python3.12/dist-packages (from triton>=2->openai-whisper) (75.2.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba->openai-whisper) (0.43.0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken->openai-whisper) (2.32.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.20.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (2025.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch->openai-whisper) (1.11.1.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken->openai-whisper) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->openai-whisper) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->openai-whisper) (3.0.3)
Building wheels for collected packages: openai-whisper
  Building wheel for openai-whisper (pyproject.toml) ... done
  Created wheel for openai-whisper: filename=openai_whisper-20250625-py3-none-any.whl size=803979 sha256=f0b9871dc30b1326c9df310ae625abadb909cbb90e434ac13d893b678752ec66
  Stored in directory: /root/.cache/pip/wheels/61/d2/20/09ec9bef734d126cba375b15898010b6cc28578d8afdde5869
Successfully built openai-whisper
Installing collected packages: openai-whisper
Successfully installed openai-whisper-20250625
Collecting language-tool-python==2.7.1
  Downloading language_tool_python-2.7.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from language-tool-python==2.7.1) (2.32.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from language-tool-python==2.7.1) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->language-tool-python==2.7.1) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->language-tool-python==2.7.1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->language-tool-python==2.7.1) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->language-tool-python==2.7.1) (2025.11.12)
Downloading language_tool_python-2.7.1-py3-none-any.whl (34 kB)
Installing collected packages: language-tool-python
Successfully installed language-tool-python-2.7.1
Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.7)
Collecting happytransformer
  Downloading happytransformer-3.0.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: librosa in /usr/local/lib/python3.12/dist-packages (0.11.0)
Requirement already satisfied: soundfile in /usr/local/lib/python3.12/dist-packages (0.13.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.5.0)
Requirement already satisfied: torch>=1.0 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (2.8.0+cu126)
Requirement already satisfied: transformers<5.0.0,>=4.30.1 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (4.57.1)
Collecting datasets<3.0.0,>=2.13.1 (from happytransformer)
  Downloading datasets-2.21.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from happytransformer) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from happytransformer) (5.29.5)
Collecting accelerate<1.0.0,>=0.20.1 (from happytransformer)
  Downloading accelerate-0.34.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: tokenizers<1.0.0,>=0.13.3 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (0.22.1)
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (from happytransformer) (0.22.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm) (1.15.3)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa) (3.0.1)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.60.0)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.0.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.2)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile) (2.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (6.0.3)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (0.6.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile) (2.23)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (3.20.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (22.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets<3.0.0,>=2.13.1->happytransformer)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (0.70.18)
Collecting fsspec<=2024.6.1,>=2023.1.0 (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets<3.0.0,>=2.13.1->happytransformer)
  Downloading fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (3.13.2)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.12/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.0->librosa) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (4.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.11.12)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (3.5)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.30.1->happytransformer) (2025.11.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb->happytransformer) (3.1.45)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb->happytransformer) (2.42.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (25.4.0)

In [ ]:
## 📦 Library Imports & Environment Setup This section loads all essential Python libraries required for data processing, numerical computation, and file system access. It also verifies the availability an****d structure of the input dataset directories provided by Kaggle.

In [3]:
import os
import librosa
import soundfile as sf
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

import whisper
import language_tool_python
import spacy
from happytransformer import HappyTextToText, TTSettings

import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from scipy.stats import pearsonr

2025-12-18 11:28:45.072070: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1766057325.349770      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1766057325.432832      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1766057326.149211      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1766057326.149290      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1766057326.149294      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1766057326.149297      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [4]:
pip install happytransformer

Requirement already satisfied: happytransformer in /usr/local/lib/python3.12/dist-packages (3.0.0)
Requirement already satisfied: torch>=1.0 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (2.8.0+cu126)
Requirement already satisfied: tqdm>=4.43 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (4.67.1)
Requirement already satisfied: transformers<5.0.0,>=4.30.1 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (4.57.1)
Requirement already satisfied: datasets<3.0.0,>=2.13.1 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (2.21.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from happytransformer) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from happytransformer) (5.29.5)
Requirement already satisfied: accelerate<1.0.0,>=0.20.1 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (0.34.2)
Requirement already satisfied: tokenizers<1.0.0,>=0.13.3 in /usr/local/lib/python3.12/dist-packages (from happytransformer) (0.22.1)
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (from happytransformer) (0.22.2)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (6.0.3)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<1.0.0,>=0.20.1->happytransformer) (0.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (3.20.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (22.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (2.32.5)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (0.70.16)
Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets<3.0.0,>=2.13.1->happytransformer) (2024.6.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets<3.0.0,>=2.13.1->happytransformer) (3.13.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0->happytransformer) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.30.1->happytransformer) (2025.11.3)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from wandb->happytransformer) (8.3.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb->happytransformer) (3.1.45)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb->happytransformer) (4.5.1)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from wandb->happytransformer) (2.12.5)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb->happytransformer) (2.42.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets<3.0.0,>=2.13.1->happytransformer) (1.22.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb->happytransformer) (4.0.12)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.0->accelerate<1.0.0,>=0.20.1->happytransformer) (1.2.1rc0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb->happytransformer) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb->happytransformer) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb->happytransformer) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<3.0.0,>=2.13.1->happytransformer) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<3.0.0,>=2.13.1->happytransformer) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<3.0.0,>=2.13.1->happytransformer) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<3.0.0,>=2.13.1->happytransformer) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0->happytransformer) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0->happytransformer) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<3.0.0,>=2.13.1->happytransformer) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<3.0.0,>=2.13.1->happytransformer) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<3.0.0,>=2.13.1->happytransformer) (2025.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb->happytransformer) (5.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets<3.0.0,>=2.13.1->happytransformer) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

📄 Training Data Loading

This cell loads the training metadata from the provided CSV file, which contains audio file identifiers and their corresponding grammar scores. It also renames the columns for clarity and easier downstream processing.

In [5]:
import pandas as pd

CSV_PATH = '/kaggle/input/shl-intern-hiring-assessment-2025/dataset/csvs/train.csv'
AUDIO_DIR = '/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train'

train_df = pd.read_csv(CSV_PATH)
train_df.columns = ['filename', 'label']

print("Train samples:", len(train_df))
train_df.head()

Train samples: 409

    filename  label
0  audio_173    3.0
1  audio_138    3.0
2  audio_127    2.0
3   audio_95    2.0
4   audio_73    3.5

📁 Processed Audio Directory Setup

This cell creates a dedicated working directory to store preprocessed audio files. Using a separate directory helps preserve the original audio data and keeps intermediate outputs organized.

In [8]:
import os

PROCESSED_DIR = "/kaggle/working/processed_audio"
os.makedirs(PROCESSED_DIR, exist_ok=True)

print("PROCESSED_DIR created:", os.path.exists(PROCESSED_DIR))

PROCESSED_DIR created: True

🎧 Audio Preprocessing Pipeline

This cell preprocesses all training audio files by resampling them to a uniform sampling rate (16 kHz), normalizing audio amplitude, and saving the processed outputs to a dedicated directory. This ensures consistent audio quality and format before speech recognition.

In [14]:
import os
import librosa
import soundfile as sf
from tqdm.notebook import tqdm

# Define directories INSIDE the cell
AUDIO_DIR = '/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/train'
PROCESSED_DIR = '/kaggle/working/processed_audio'
os.makedirs(PROCESSED_DIR, exist_ok=True)

# Define preprocessing function INSIDE the cell
def preprocess_audio(file_path, save_path, target_sr=16000):
    y, sr = librosa.load(file_path, sr=None)
    if sr != target_sr:
        y = librosa.resample(y=y, orig_sr=sr, target_sr=target_sr)
    y = y / max(abs(y)) if max(abs(y)) > 0 else y
    sf.write(save_path, y, target_sr)

# Preprocess all training audio
processed_count = 0

for fname in tqdm(train_df['filename']):
    in_path = os.path.join(AUDIO_DIR, fname)
    out_path = os.path.join(PROCESSED_DIR, fname)

    if os.path.exists(in_path):
        preprocess_audio(in_path, out_path)
        processed_count += 1

print("Processed files:", processed_count)
print("Sample processed files:", os.listdir(PROCESSED_DIR)[:5])

  0%|          | 0/409 [00:00<?, ?it/s]

/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/1492229719.py:13: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

Processed files: 409
Sample processed files: ['audio_105.wav', 'audio_9.wav', 'audio_40.wav', 'audio_48.wav', 'audio_34_2.wav']

📥 Whisper Installation

This cell installs the OpenAI Whisper library, which is used for automatic speech recognition (ASR) to convert audio files into text transcripts.

In [17]:
!pip install -q openai-whisper

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.2/803.2 kB 10.6 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for openai-whisper (pyproject.toml) ... done

🗣️ Speech-to-Text Transcription (Whisper ASR)

This cell uses the OpenAI Whisper model to transcribe preprocessed training audio files into text. The resulting transcripts form the core linguistic input for subsequent grammar analysis and feature extraction.

In [18]:
import os
from tqdm.notebook import tqdm
import whisper

# Define processed audio directory INSIDE the cell
PROCESSED_DIR = '/kaggle/working/processed_audio'

# Load Whisper model
model_whisper = whisper.load_model("base")

transcripts = []

for fname in tqdm(train_df['filename']):
    audio_path = os.path.join(PROCESSED_DIR, fname)
    result = model_whisper.transcribe(
        audio_path,
        language="en",
        fp16=False
    )
    transcripts.append(result["text"])

# Attach transcripts
train_df['transcript'] = transcripts

print("✅ Whisper transcription completed.")
train_df[['filename', 'transcript']].head()

100%|████████████████████████████████████████| 139M/139M [00:00<00:00, 259MiB/s]

  0%|          | 0/409 [00:00<?, ?it/s]

✅ Whisper transcription completed.

        filename                                         transcript
0  audio_173.wav   My favorite place to visit will be Japan, bec...
1  audio_138.wav   I love to reading on my hobby such reading. E...
2  audio_127.wav   My favorite place to visit is the Mullahites ...
3   audio_95.wav   I am going to tell about my hobby. And my hob...
4   audio_73.wav   This is a tough one. So my bestie of my life ...

🔍 Filename & Audio File Consistency Check

This cell verifies that the filenames listed in the training CSV match the actual audio files present in the processed_audio directory. This helps catch common issues such as missing file extensions or mismatched filenames before running Whisper or feature extraction.

In [12]:
# Check what filenames look like in CSV
print(train_df['filename'].head())

# Check what files actually exist
print("\nSample files in processed_audio:")
print(os.listdir(PROCESSED_DIR)[:10])

0    audio_173
1    audio_138
2    audio_127
3     audio_95
4     audio_73
Name: filename, dtype: object

Sample files in processed_audio:
[]

🧩 Filename Normalization (.wav Extension Fix)

This cell ensures that all audio filenames listed in the training DataFrame include the .wav extension. Since the actual audio files are stored as .wav, this step prevents file-not-found errors during preprocessing and transcription.

In [13]:
# Add .wav extension if missing
train_df['filename'] = train_df['filename'].apply(
    lambda x: x if x.endswith('.wav') else f"{x}.wav"
)

# Verify
print(train_df['filename'].head())

0    audio_173.wav
1    audio_138.wav
2    audio_127.wav
3     audio_95.wav
4     audio_73.wav
Name: filename, dtype: object

🧪 Processed Audio Integrity Check

This cell verifies that every training audio file listed in the CSV has a corresponding preprocessed .wav file in the processed_audio directory. It helps confirm that the audio preprocessing step completed successfully for all samples.

In [14]:
# Check if all processed audio files exist
missing_files = []

for fname in train_df['filename']:
    if not os.path.exists(os.path.join(PROCESSED_DIR, fname)):
        missing_files.append(fname)

print("Total training files:", len(train_df))
print("Missing processed audio files:", len(missing_files))
print("Example missing files:", missing_files[:5])

Total training files: 409
Missing processed audio files: 409
Example missing files: ['audio_173.wav', 'audio_138.wav', 'audio_127.wav', 'audio_95.wav', 'audio_73.wav']

In [15]:
# Clear old processed_audio directory
import shutil

shutil.rmtree(PROCESSED_DIR)
os.makedirs(PROCESSED_DIR, exist_ok=True)

print("Old processed_audio cleared.")

Old processed_audio cleared.

🎧 Audio Preprocessing Function Definition

This cell defines the preprocess_audio function, which standardizes raw audio files before transcription and feature extraction.

In [16]:
def preprocess_audio(file_path, save_path, sr=16000):
    y, orig_sr = librosa.load(file_path, sr=None)
    if orig_sr != sr:
        y = librosa.resample(y, orig_sr, sr)
    y = y / max(abs(y))
    sf.write(save_path, y, sr)

print("preprocess_audio function defined.")

preprocess_audio function defined.

🔁 Audio Preprocessing Function (Redefined – Librosa-Compatible)

This cell redefines the same preprocess_audio function, with a small but important fix to make it compatible with newer versions of librosa

In [17]:
def preprocess_audio(file_path, save_path, sr=16000):
    y, orig_sr = librosa.load(file_path, sr=None)

    if orig_sr != sr:
        y = librosa.resample(y, orig_sr=orig_sr, target_sr=sr)

    y = y / max(abs(y))
    sf.write(save_path, y, sr)

print("preprocess_audio function redefined (librosa-compatible).")

preprocess_audio function redefined (librosa-compatible).

🔄 Audio Preprocessing Execution (Training Set)

This cell applies the audio preprocessing function to every training audio file and saves the standardized versions into the processed_audio directory.

In [18]:
for filename in tqdm(train_df['filename']):
    in_path = os.path.join(AUDIO_DIR, filename)
    out_path = os.path.join(PROCESSED_DIR, filename)
    preprocess_audio(in_path, out_path)

print("Audio preprocessing completed successfully.")

  0%|          | 0/409 [00:00<?, ?it/s]

/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/2534552399.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, orig_sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load

Audio preprocessing completed successfully.

In [21]:
# Verify processed audio files again
missing_files = []

for fname in train_df['filename']:
    if not os.path.exists(os.path.join(PROCESSED_DIR, fname)):
        missing_files.append(fname)

print("Total training files:", len(train_df))
print("Missing processed audio files:", len(missing_files))
print("Example missing files:", missing_files[:5])

Total training files: 409
Missing processed audio files: 0
Example missing files: []

In [22]:
# Load Whisper model
model_whisper = whisper.load_model("base")

# Transcribe processed audio
transcripts = []

for fname in tqdm(train_df['filename']):
    audio_path = os.path.join(PROCESSED_DIR, fname)
    result = model_whisper.transcribe(
        audio_path,
        language="en",
        fp16=False   # IMPORTANT for Kaggle stability
    )
    transcripts.append(result["text"])

# Attach transcripts
train_df['transcript'] = transcripts

print("Whisper transcription completed.")

  0%|          | 0/409 [00:00<?, ?it/s]

Whisper transcription completed.

In [23]:
# Save transcripts immediately (important)
train_df.to_csv('/kaggle/working/train_with_transcripts.csv', index=False)

print("Transcripts saved safely.")
train_df[['filename', 'transcript']].head()

Transcripts saved safely.

        filename                                         transcript
0  audio_173.wav   My favorite place to visit will be Japan, bec...
1  audio_138.wav   I love to reading on my hobby such reading. E...
2  audio_127.wav   My favorite place to visit is the Mullahites ...
3   audio_95.wav   I am going to tell about my hobby. And my hob...
4   audio_73.wav   This is a tough one. So my bestie of my life ...

In [24]:
import re

FILLERS = ['uh', 'um', 'erm', 'you know', 'like', 'i mean', 'hmm', 'ah', 'uhh', 'huh']

def clean_transcript(text):
    text = text.lower()
    text = re.sub(r'\b(?:' + '|'.join(FILLERS) + r')\b', '', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\s([?.!,"])', r'\1', text)
    return text.strip()

train_df['cleaned_transcript'] = train_df['transcript'].astype(str).apply(clean_transcript)

print("Transcript cleaning completed.")
train_df[['transcript', 'cleaned_transcript']].head()

Transcript cleaning completed.

,transcript,cleaned_transcript
0,"My favorite place to visit will be Japan, bec...","my favorite place to visit will be japan, beca..."
1,I love to reading on my hobby such reading. E...,i love to reading on my hobby such reading. em...
2,My favorite place to visit is the Mullahites ...,my favorite place to visit is the mullahites n...
3,I am going to tell about my hobby. And my hob...,i am going to tell about my hobby. and my hobb...
4,This is a tough one. So my bestie of my life ...,this is a tough one. so my bestie of my life i...

In [25]:
import language_tool_python

# Use public LanguageTool server (NO local download, NO Java)
tool = language_tool_python.LanguageToolPublicAPI('en-US')

print("LanguageTool initialized using remote API.")

LanguageTool initialized using remote API.

In [26]:
import spacy
from happytransformer import HappyTextToText, TTSettings
from tqdm.notebook import tqdm

# NLP + GEC models
nlp = spacy.load("en_core_web_sm")

happy_tt = HappyTextToText("T5", "vennify/t5-base-grammar-correction")
args = TTSettings(num_beams=5, min_length=1)

# Feature containers
avg_sent_lengths = []
pos_diversities = []
word_counts = []
gec_edits = []
gec_rates = []

for text in tqdm(train_df['cleaned_transcript']):
    # NLP features
    doc = nlp(text)
    sent_lens = [len(sent) for sent in doc.sents]
    pos_tags = [token.pos_ for token in doc if token.pos_ != 'SPACE']

    avg_sent_lengths.append(sum(sent_lens) / len(sent_lens) if sent_lens else 0)
    pos_diversities.append(len(set(pos_tags)))

    # Word count
    words = text.split()
    wc = len(words)
    word_counts.append(wc)

    # Grammar correction edits
    corrected = happy_tt.generate_text("grammar: " + text, args=args).text
    corr_words = corrected.split()

    edits = sum(1 for o, c in zip(words, corr_words) if o != c)
    edits += abs(len(words) - len(corr_words))

    gec_edits.append(edits)
    gec_rates.append(edits / max(1, wc))

# Attach features (NO LanguageTool)
train_df['avg_sentence_length'] = avg_sent_lengths
train_df['pos_diversity'] = pos_diversities
train_df['word_count'] = word_counts
train_df['gec_edits'] = gec_edits
train_df['gec_edit_rate'] = gec_rates

print("Feature extraction completed (LanguageTool removed).")
train_df.head()

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/892M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

  0%|          | 0/409 [00:00<?, ?it/s]

Device set to use cpu
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Feature extraction completed (LanguageTool removed).

,filename,label,transcript,cleaned_transcript,avg_sentence_length,pos_diversity,word_count,gec_edits,gec_edit_rate
0,audio_173.wav,3.0,"My favorite place to visit will be Japan, bec...","my favorite place to visit will be japan, beca...",15.000000,14,89,54,0.606742
1,audio_138.wav,3.0,I love to reading on my hobby such reading. E...,i love to reading on my hobby such reading. em...,26.833333,15,153,153,1.000000
2,audio_127.wav,2.0,My favorite place to visit is the Mullahites ...,my favorite place to visit is the mullahites n...,10.000000,12,61,2,0.032787
3,audio_95.wav,2.0,I am going to tell about my hobby. And my hob...,i am going to tell about my hobby. and my hobb...,16.166667,12,86,29,0.337209
4,audio_73.wav,3.5,This is a tough one. So my bestie of my life ...,this is a tough one. so my bestie of my life i...,13.700000,13,120,53,0.441667

In [28]:
import os
from tqdm.notebook import tqdm
import whisper

# Define paths INSIDE the cell
PROCESSED_DIR = '/kaggle/working/processed_audio'

# Load Whisper model
model_whisper = whisper.load_model("base")

transcripts = []

for fname in tqdm(train_df['filename']):
    audio_path = os.path.join(PROCESSED_DIR, fname)

    result = model_whisper.transcribe(
        audio_path,
        language='en',
        fp16=False
    )

    transcripts.append(result['text'])

# Add transcript column
train_df['transcript'] = transcripts

print("✅ Whisper transcription completed.")
train_df[['filename', 'transcript']].head()

  0%|          | 0/409 [00:00<?, ?it/s]

✅ Whisper transcription completed.

        filename                                         transcript
0  audio_173.wav   My favorite place to visit will be Japan, bec...
1  audio_138.wav   I love to reading on my hobby such reading. E...
2  audio_127.wav   My favorite place to visit is the Mullahites ...
3   audio_95.wav   I am going to tell about my hobby. And my hob...
4   audio_73.wav   This is a tough one. So my bestie of my life ...

In [29]:
import re

FILLERS = ['uh', 'um', 'erm', 'you know', 'like', 'i mean', 'hmm', 'ah', 'uhh', 'huh']

def clean_transcript(text):
    text = text.lower()
    text = re.sub(r'\b(?:' + '|'.join(FILLERS) + r')\b', '', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\s([?.!,"])', r'\1', text)
    return text.strip()

train_df['cleaned_transcript'] = train_df['transcript'].astype(str).apply(clean_transcript)

print("✅ Transcript cleaning completed.")
train_df[['transcript', 'cleaned_transcript']].head()

✅ Transcript cleaning completed.

,transcript,cleaned_transcript
0,"My favorite place to visit will be Japan, bec...","my favorite place to visit will be japan, beca..."
1,I love to reading on my hobby such reading. E...,i love to reading on my hobby such reading. em...
2,My favorite place to visit is the Mullahites ...,my favorite place to visit is the mullahites n...
3,I am going to tell about my hobby. And my hob...,i am going to tell about my hobby. and my hobb...
4,This is a tough one. So my bestie of my life ...,this is a tough one. so my bestie of my life i...

In [30]:
import spacy

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

avg_sentence_length = []
pos_diversity = []
word_count = []

for text in train_df['cleaned_transcript']:
    doc = nlp(text)

    # Average sentence length
    sent_lengths = [len(sent) for sent in doc.sents]
    avg_sentence_length.append(
        sum(sent_lengths) / len(sent_lengths) if sent_lengths else 0
    )

    # POS diversity
    pos_tags = [token.pos_ for token in doc if token.pos_ != 'SPACE']
    pos_diversity.append(len(set(pos_tags)))

    # Word count
    word_count.append(len(text.split()))

# Add features to dataframe
train_df['avg_sentence_length'] = avg_sentence_length
train_df['pos_diversity'] = pos_diversity
train_df['word_count'] = word_count

print("✅ Basic text features extracted.")
train_df[['avg_sentence_length', 'pos_diversity', 'word_count']].head()

✅ Basic text features extracted.

   avg_sentence_length  pos_diversity  word_count
0            15.000000             14          89
1            26.833333             15         153
2            10.000000             12          61
3            16.166667             12          86
4            13.700000             13         120

In [31]:
import lightgbm as lgb
import numpy as np
from sklearn.metrics import mean_squared_error
from scipy.stats import pearsonr

# Feature matrix and target
features = ['avg_sentence_length', 'pos_diversity', 'word_count']
X = train_df[features]
y = train_df['label']

# LightGBM Regressor
lgb_model = lgb.LGBMRegressor(
    n_estimators=200,
    learning_rate=0.05,
    random_state=42
)

# Train on full training data
lgb_model.fit(X, y)

# Training predictions
train_preds = lgb_model.predict(X)

# Metrics (MANDATORY)
rmse = np.sqrt(mean_squared_error(y, train_preds))
pearson = pearsonr(y, train_preds)[0]

print(f"✅ Training RMSE: {rmse:.3f}")
print(f"✅ Training Pearson Correlation: {pearson:.3f}")

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001309 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 223
[LightGBM] [Info] Number of data points in the train set: 409, number of used features: 3
[LightGBM] [Info] Start training from score 2.910758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
✅ Training RMSE: 0.524
✅ Training Pearson Correlation: 0.759

In [33]:
import os
import pandas as pd
import numpy as np

# -----------------------------
# 1. Load test CSV
# -----------------------------
TEST_CSV_PATH = '/kaggle/input/shl-intern-hiring-assessment-2025/dataset/csvs/test.csv'
TEST_AUDIO_DIR = '/kaggle/input/shl-intern-hiring-assessment-2025/dataset/audios/test'
PROCESSED_TEST_DIR = '/kaggle/working/processed_test_audio'

os.makedirs(PROCESSED_TEST_DIR, exist_ok=True)

test_df = pd.read_csv(TEST_CSV_PATH)
test_df.columns = ['filename']

# Ensure .wav extension
test_df['filename'] = test_df['filename'].apply(
    lambda x: x if x.endswith('.wav') else f"{x}.wav"
)

print("Test samples:", len(test_df))


# -----------------------------
# 2. Preprocess test audio
# -----------------------------
import librosa
import soundfile as sf
from tqdm.notebook import tqdm

def preprocess_audio(file_path, save_path, target_sr=16000):
    y, sr = librosa.load(file_path, sr=None)
    if sr != target_sr:
        y = librosa.resample(y=y, orig_sr=sr, target_sr=target_sr)
    y = y / max(abs(y)) if max(abs(y)) > 0 else y
    sf.write(save_path, y, target_sr)

for fname in tqdm(test_df['filename']):
    in_path = os.path.join(TEST_AUDIO_DIR, fname)
    out_path = os.path.join(PROCESSED_TEST_DIR, fname)
    preprocess_audio(in_path, out_path)

print("✅ Test audio preprocessing done.")


# -----------------------------
# 3. Whisper transcription
# -----------------------------
import whisper

model_whisper = whisper.load_model("base")
test_transcripts = []

for fname in tqdm(test_df['filename']):
    audio_path = os.path.join(PROCESSED_TEST_DIR, fname)
    result = model_whisper.transcribe(audio_path, language='en', fp16=False)
    test_transcripts.append(result['text'])

test_df['transcript'] = test_transcripts
print("✅ Test transcription done.")


# -----------------------------
# 4. Clean transcripts
# -----------------------------
import re

FILLERS = ['uh', 'um', 'erm', 'you know', 'like', 'i mean', 'hmm', 'ah', 'uhh', 'huh']

def clean_transcript(text):
    text = text.lower()
    text = re.sub(r'\b(?:' + '|'.join(FILLERS) + r')\b', '', text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r'\s([?.!,"])', r'\1', text)
    return text.strip()

test_df['cleaned_transcript'] = test_df['transcript'].astype(str).apply(clean_transcript)


# -----------------------------
# 5. Feature extraction (same as train)
# -----------------------------
import spacy
nlp = spacy.load("en_core_web_sm")

avg_sentence_length = []
pos_diversity = []
word_count = []

for text in test_df['cleaned_transcript']:
    doc = nlp(text)
    sent_lengths = [len(sent) for sent in doc.sents]
    avg_sentence_length.append(
        sum(sent_lengths) / len(sent_lengths) if sent_lengths else 0
    )
    pos_tags = [token.pos_ for token in doc if token.pos_ != 'SPACE']
    pos_diversity.append(len(set(pos_tags)))
    word_count.append(len(text.split()))

test_df['avg_sentence_length'] = avg_sentence_length
test_df['pos_diversity'] = pos_diversity
test_df['word_count'] = word_count


# -----------------------------
# 6. Predict using trained LightGBM
# -----------------------------
features = ['avg_sentence_length', 'pos_diversity', 'word_count']
X_test = test_df[features]

test_preds = lgb_model.predict(X_test)

# Clip to valid range
test_preds = np.clip(test_preds, 0, 5)

test_df['label'] = test_preds


# -----------------------------
# 7. Create submission file
# -----------------------------
submission = test_df[['filename', 'label']]
submission.to_csv('/kaggle/working/submission.csv', index=False)

print("✅ submission.csv created successfully")
submission.head()

Test samples: 197

  0%|          | 0/197 [00:00<?, ?it/s]

/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/tmp/ipykernel_55/20357853.py:33: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(file_path, sr=None)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

✅ Test audio preprocessing done.

  0%|          | 0/197 [00:00<?, ?it/s]

✅ Test transcription done.
✅ submission.csv created successfully

        filename     label
0  audio_141.wav  2.805552
1  audio_114.wav  2.202687
2   audio_17.wav  2.885220
3   audio_76.wav  3.742531
4  audio_156.wav  2.435042

In [32]:
submission = test_df[['filename', 'label']]
submission.to_csv('/kaggle/working/submission.csv', index=False)

print("✅ submission.csv created successfully")
submission.head()

NameError: name 'test_df' is not defined

In [25]:
import whisper
print("Whisper imported successfully")

Whisper imported successfully

In [27]:
import pandas as pd

# Reload training data from saved CSV
train_df = pd.read_csv('/kaggle/working/train_with_transcripts.csv')

print("train_df loaded")
print("Shape:", train_df.shape)
train_df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/train_with_transcripts.csv'

In [22]:
import pandas as pd

# Load original training CSV from input (this is persistent)
CSV_PATH = '/kaggle/input/shl-intern-hiring-assessment-2025/dataset/csvs/train.csv'
train_df = pd.read_csv(CSV_PATH)
train_df.columns = ['filename', 'label']

print("train_df loaded from input")
print(train_df.shape)
train_df.head()

train_df loaded from input
(409, 2)

    filename  label
0  audio_173    3.0
1  audio_138    3.0
2  audio_127    2.0
3   audio_95    2.0
4   audio_73    3.5

In [23]:
train_df['filename'] = train_df['filename'].apply(
    lambda x: x if x.endswith('.wav') else f"{x}.wav"
)

print(train_df['filename'].head())

0    audio_173.wav
1    audio_138.wav
2    audio_127.wav
3     audio_95.wav
4     audio_73.wav
Name: filename, dtype: object